### ISSUE TITLE
Source class "\Emizentech\Priceslider\Block\FilterRenderer" does not exist....

### ISSUE THREAD

**Issue by sscraggles** [emizentech/magento2-price-slider#2]
Hi,
I would really like to be able to use this, but I get the following error....
(using php 7.0.6 on Apache)

Source class "\Emizentech\Priceslider\Block\FilterRenderer" for "Emizentech\Priceslider\Block\FilterRenderer\Interceptor" generation does not exist.
#0 /var/www/vendor/magento/framework/Code/Generator.php(100): Magento\Framework\Code\Generator->tryToLoadSourceClass('Emizentech\Pric...', Object(Magento\Framework\Interception\Code\Generator\Interceptor))
#1 /var/www/vendor/magento/framework/Code/Generator/Autoloader.php(35): Magento\Framework\Code\Generator->generateClass('Emizentech\Pric...')
#2 [internal function]: Magento\Framework\Code\Generator\Autoloader->load('Emizentech\Pric...')
#3 [internal function]: spl_autoload_call('Emizentech\Pric...')
#4 /var/www/vendor/magento/framework/Code/Reader/ClassReader.php(19): ReflectionClass->__construct('Emizentech\Pric...')
#5 /var/www/vendor/magento/framework/ObjectManager/Definition/Runtime.php(44): Magento\Framework\Code\Reader\ClassReader->getConstructor('Emizentech\Pric...')
#6 /var/www/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(71): Magento\Framework\ObjectManager\Definition\Runtime->getParameters('Emizentech\Pric...')
#7 /var/www/vendor/magento/framework/ObjectManager/ObjectManager.php(57): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Emizentech\Pric...', Array)
#8 /var/www/vendor/magento/framework/View/Element/BlockFactory.php(43): Magento\Framework\ObjectManager\ObjectManager->create('Magento\Layered...', Array)
#9 /var/www/vendor/magento/framework/View/Layout/Generator/Block.php(256): Magento\Framework\View\Element\BlockFactory->createBlock('Magento\Layered...', Array)
#10 /var/www/vendor/magento/framework/View/Layout/Generator/Block.php(237): Magento\Framework\View\Layout\Generator\Block->getBlockInstance('Magento\Layered...', Array)
#11 /var/www/vendor/magento/framework/View/Layout/Generator/Block.php(215): Magento\Framework\View\Layout\Generator\Block->createBlock('Magento\Layered...', 'catalog.navigat...', Array)
#12 /var/www/vendor/magento/framework/View/Layout/Generator/Block.php(124): Magento\Framework\View\Layout\Generator\Block->generateBlock(Object(Magento\Framework\View\Layout\ScheduledStructure), Object(Magento\Framework\View\Layout\Data\Structure), 'catalog.navigat...')
#13 /var/www/vendor/magento/framework/View/Layout/GeneratorPool.php(86): Magento\Framework\View\Layout\Generator\Block->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#14 /var/www/vendor/magento/framework/View/Layout.php(327): Magento\Framework\View\Layout\GeneratorPool->process(Object(Magento\Framework\View\Layout\Reader\Context), Object(Magento\Framework\View\Layout\Generator\Context))
#15 /var/www/var/generation/Magento/Framework/View/Layout/Interceptor.php(89): Magento\Framework\View\Layout->generateElements()
#16 /var/www/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements()
#17 /var/www/vendor/magento/framework/View/Page/Builder.php(55): Magento\Framework\View\Layout\Builder->generateLayoutBlocks()
#18 /var/www/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks()
#19 /var/www/vendor/magento/framework/View/Page/Config.php(187): Magento\Framework\View\Layout\Builder->build()
#20 /var/www/vendor/magento/framework/View/Page/Config.php(499): Magento\Framework\View\Page\Config->build()
#21 /var/www/vendor/magento/framework/View/Page/Config.php(457): Magento\Framework\View\Page\Config->getElementAttribute('body', 'class')
#22 /var/www/vendor/magento/module-catalog/Controller/Category/View.php(198): Magento\Framework\View\Page\Config->addBodyClass('page-products')
#23 /var/www/var/generation/Magento/Catalog/Controller/Category/View/Interceptor.php(24): Magento\Catalog\Controller\Category\View->execute()
#24 /var/www/vendor/magento/framework/App/Action/Action.php(102): Magento\Catalog\Controller\Category\View\Interceptor->execute()
#25 [internal function]: Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#26 /var/www/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#27 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Catalog\Controller\Category\View\Interceptor->___callParent('dispatch', Array)
#28 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Category\View\Interceptor), Array, 'designLoader')
#29 /var/www/vendor/magento/framework/App/Action/Plugin/Design.php(39): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#30 [internal function]: Magento\Framework\App\Action\Plugin\Design->aroundDispatch(Object(Magento\Catalog\Controller\Category\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#32 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Category\View\Interceptor), Array, 'contextPlugin')
#33 /var/www/vendor/magento/module-store/App/Action/Plugin/Context.php(106): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#34 [internal function]: Magento\Store\App\Action\Plugin\Context->aroundDispatch(Object(Magento\Catalog\Controller\Category\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#35 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#36 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Category\View\Interceptor), Array, 'customer-app-ac...')
#37 /var/www/vendor/magento/module-customer/Model/App/Action/ContextPlugin.php(61): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#38 [internal function]: Magento\Customer\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Catalog\Controller\Category\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#39 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#40 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Category\View\Interceptor), Array, 'storeCheck')
#41 /var/www/vendor/magento/module-store/App/Action/Plugin/StoreCheck.php(44): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#42 [internal function]: Magento\Store\App\Action\Plugin\StoreCheck->aroundDispatch(Object(Magento\Catalog\Controller\Category\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#43 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#44 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Category\View\Interceptor), Array, 'weee-app-action...')
#45 /var/www/vendor/magento/module-weee/Model/App/Action/ContextPlugin.php(112): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#46 [internal function]: Magento\Weee\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Catalog\Controller\Category\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#47 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#48 /var/www/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Catalog...', 'dispatch', Object(Magento\Catalog\Controller\Category\View\Interceptor), Array, 'tax-app-action-...')
#49 /var/www/vendor/magento/module-tax/Model/App/Action/ContextPlugin.php(110): Magento\Catalog\Controller\Category\View\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#50 [internal function]: Magento\Tax\Model\App\Action\ContextPlugin->aroundDispatch(Object(Magento\Catalog\Controller\Category\View\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#51 /var/www/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#52 /var/www/var/generation/Magento/Catalog/Controller/Category/View/Interceptor.php(39): Magento\Catalog\Controller\Category\View\Interceptor->___callPlugins('dispatch', Array, Array)
#53 /var/www/vendor/magento/framework/App/FrontController.php(55): Magento\Catalog\Controller\Category\View\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#54 [internal function]: Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#55 /var/www/vendor/magento/framework/Interception/Interceptor.php(74): call_user_func_array(Array, Array)
#56 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(70): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#57 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'requestPreproce...')
#58 /var/www/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(89): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#59 [internal function]: Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#60 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#61 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'install')
#62 /var/www/vendor/magento/framework/Module/Plugin/DbStatusValidator.php(69): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#63 [internal function]: Magento\Framework\Module\Plugin\DbStatusValidator->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#64 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#65 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(63): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#66 /var/www/vendor/magento/module-page-cache/Model/App/FrontController/VarnishPlugin.php(55): Magento\Framework\Interception\Chain\Chain->Magento\Framework\Interception\Chain{closure}(Object(Magento\Framework\App\Request\Http))
#67 [internal function]: Magento\PageCache\Model\App\FrontController\VarnishPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#68 /var/www/vendor/magento/framework/Interception/Chain/Chain.php(67): call_user_func_array(Array, Array)
#69 /var/www/vendor/magento/framework/Interception/Interceptor.php(136): Magento\Framework\Interception\Chain\Chain->invokeNext('Magento\Framewo...', 'dispatch', Object(Magento\Framework\App\FrontController\Interceptor), Array, 'front-controlle...')
#70 /var/www/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception{closure}(Object(Magento\Framework\App\Request\Http))
#71 [internal function]: Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#72 /var/www/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array)
#73 /var/www/var/generation/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#74 /var/www/vendor/magento/framework/App/Http.php(115): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#75 /var/www/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#76 /var/www/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#77 {main}

**Comment by sscraggles** [comment]
I also get an error when I try to install via composer....

$ composer require emizentech/priceslider  
  [InvalidArgumentException]  
  Could not find package emizentech/priceslider at any version matching your PHP version 7.0.7.0
